### Create User
@baseUrl = http://localhost:3000
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "test1@email.com",
  "password": "test1"
}

### Sign In
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "email": "test1@email.com",
  "password": "test1"
}

### Sign Out
POST {{baseUrl}}/auth/signout

### Remove User
DELETE {{baseUrl}}/auth/7

### Get the currently signed user
GET {{baseUrl}}/auth/whoami

### Get User by ID
GET {{baseUrl}}/auth/1

### Get Users by Email
GET {{baseUrl}}/auth?email=test@email.com

### Update User by ID
PATCH {{baseUrl}}/auth/1
Content-Type: application/json

{
  "password": "aaaa"
}
