### Create User
@baseUrl = http://localhost:3000
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "test"
}

### Remove User
DELETE {{baseUrl}}/auth/6

### Get User by ID
GET {{baseUrl}}/auth/1

### Get Users by Email
GET {{baseUrl}}/auth?email=test@email.com

### Update User by ID
PATCH {{baseUrl}}/auth/1
Content-Type: application/json

{
  "password": "aaaa"
}