@baseUrl = http://localhost:3000/auth

### Create User
POST {{baseUrl}}/signup
Content-Type: application/json

{
  "email": "test4@email.com",
  "password": "test4"
}

### Sign In
POST {{baseUrl}}/signin
Content-Type: application/json

{
  "email": "test3@email.com",
  "password": "test3"
}

### Sign Out
POST {{baseUrl}}/signout

### Remove User
DELETE {{baseUrl}}/14

### Get the currently signed user
GET {{baseUrl}}/whoami

### Get User by ID
GET {{baseUrl}}/1

### Get Users by Email
GET {{baseUrl}}?email=test@email.com

### Update User by ID
PATCH {{baseUrl}}/1
Content-Type: application/json

{
  "password": "aaaa"
}
